START /B pandoc -t beamer -V theme:Singapore slides.md -o a_singapore.pdf
START /B pandoc -t beamer -V theme:Rochester slides.md -o a_rochester.pdf
START /B pandoc -t beamer -V theme:Warsaw slides.md -o a_warsaw.pdf
START /B pandoc -t beamer -V theme:Szeged slides.md -o a_szeged.pdf
START /B pandoc -t beamer -V theme:Pittsburgh slides.md -o a_pittsburgh.pdf
START /B pandoc -t beamer -V theme:PaloAlto slides.md -o a_PaloAlto.pdf
START /B pandoc -t beamer -V theme:Marburg slides.md -o a_Marburg.pdf
START /B pandoc -t beamer -V theme:Malmoe slides.md -o a_Malmoe.pdf
START /B pandoc slides.md -o myslides.pptx
START /B pandoc slides.md -o myslides.odt
